### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by awernick** [vyder/spacegray-chalk#1]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `spacegray-chalk-syntax` package

```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:460:9)
ThemePackage.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:471:32)
ThemePackage.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:453:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:47:19)
ThemePackage.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:43:12)
```

**Comment by vyder** [comment]
I managed to muck up the tags in the remote repository somehow, so I ended up bumping the major version all the way up to 4.0 and published this package on Atom instead of untangling the git mess.

I don't use Atom anymore, so let me know if this is still an issue for you. (Better yet, create a PR!)
